### ISSUE TITLE
(Unimportant bug) Incorrect suits spawning

### ISSUE THREAD

**Issue by Anonym-12321** [AndreyMrovol/LethalUnlockOnStart#11]
This is a weird one.
It happened only once yesterday and i don't know how to reproduce it, it never happened again so far.
v0.6.2
My suit settings were purple suit and hazard suit, the lobby was just created and i sadly forgot to save the log for the post.
![what](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/4a32670d-3d06-479e-9975-bd470c6ea081)

**Comment by Anonym-12321** [comment]
Today i have realised that i can get this to consistently happen by creating the save file, quitting and reloading it.
I'm marking this as not important since it does not ruin any important save and the user can get around it by creating a new file.

Also while i'm at it i may as well mention an older bug that happens with the same procedure is starter items duplicating, also not really important for the same reasons.

**Comment by AndreyMrovol** [comment]
Hey, thanks for digging deeper into this - I've encountered this bug a few times myself, but it's a result of the implementation - mod checks for saved data and if it's the first day, then spawns items. In a case you described there is no saved data, so items spawn.
