### ISSUE TITLE
Issue with MoreAdditionalSuits

### ISSUE THREAD

**Issue by TheRealMrKam** [AndreyMrovol/LethalUnlockOnStart#12]
Hello, i found an issue between UnlockOnStart and this mod : https://thunderstore.io/c/lethal-company/p/ChooMcoo/MoreAdditionalSuits/

What happen is when i load the game the suits are on the rack, but if i quit the game and reload the save, they disapear.

Here is the log :
[LogOutput.log](https://github.com/AndreyMrovol/LethalUnlockOnStart/files/14411954/LogOutput.log)

**Comment by AndreyMrovol** [comment]
Hey, this issue has been reported to me before (although issues on this repo got removed - weird), and it's not something I'm planning to address, sadly.

The way it works/breaks is: If you enter a new save the suits are spawned, but if you leave before the game save all items & suits will be added again, causing issues (cause it's still 0 day in-game).

**Comment by TheRealMrKam** [comment]
So does the bug affects only the first day ? if i quit on day 2 it will be fine ?

**Comment by AndreyMrovol** [comment]
AFAIK it's a first day issue - if you encounter any bugs in later days please let me know.

**Comment by TheRealMrKam** [comment]
Well, i guess it's an ok bug if it's  only the first day since you can just reset the run anyway ! Thanks for the infos !
