### ISSUE TITLE
Plushie Pajama Man option not working

### ISSUE THREAD

**Issue by Re-VelatoR** [AndreyMrovol/LethalUnlockOnStart#2]
Plushie Pajama Man unlock option does nothing. I have everything selected except for the suits, shower, and toilet.

**Comment by AndreyMrovol** [comment]
@Re-VelatoR Hey, thanks for reporting the issue - I copied wrong variable into my file (_sorry!_). I've just pushed v0.3.1 to Thunderstore, please check if it resolves your issue.

**Comment by Anonym-12321** [comment]
It seems to be working now
![image](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/65e0fada-5798-4b99-9e06-387cd2fac8aa)
