### ISSUE TITLE
Weird behaviour between UnlockOnStart and mods that spawn shotguns and shells in maps

### ISSUE THREAD

**Issue by Anonym-12321** [AndreyMrovol/LethalUnlockOnStart#3]
Changing the Shotgun Shells setting above 0 does not lead to shotgun shells to appear. It seems to be consistently broken, i don't know if they're just out of sight, but i think that they're not spawning.

**Comment by AndreyMrovol** [comment]
Hey, thanks for the report - from my testing it's working as intended.

![image](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/32998721/4ce7b761-87a0-490f-8919-ac39b0a6f9de)
with UnlockOnStart v0.3.1 and config: `Ammo/Shotgun shells` 66, `Shotgun/Shotgun` 2

**Comment by Anonym-12321** [comment]
Hello! Thank you very much for the feedback,

After doing some more testing, i realised that it isn't an issue with this mod, it was just another mod interfering with it.
For some reason, BetterShotgunShells v1.0.2 seems to prevent the shells from spawning, probably because it adds shell spawn rates to high tier moons which somehow messes with them in your mod.
I switched over to BuyableShotgunShells v1.0.4 (different mod and author) and it all seems to work well.

I don't think that this issue needs to stay open anymore, so i'm closing it.

**Comment by Anonym-12321** [comment]
.

**Comment by Anonym-12321** [comment]
Apologies in advance from reopening this, i couldn't help myself from start digging.

I made and compared two logs:
(UnlockOnStart v0.6.1 at the left and UnlockOnStart v0.6.1 + BetterShotgun v1.0.1 on the right)
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/67f096fb-d466-424c-a8b5-abd7a83f2b28)
Apparently, it seems that to spawn shotguns and shells, BetterShotgun for some reason renames Ammo to Shell, and also adds two shotgun variants and one shell variant. I haven't checked back the other mod yet, but it is interesting that both mods ended up messing with the shells. (I haven't checked back on the other shells mod which i originally found the issue with, but this one was more featureful so i just tested this one instead)

I have no idea which mod of the two is supposed to recieve changes for better compatibility, i'd probably have to get a full grasp myself about the inner workings of both mods, so i won't judge.

After tinkering around i did make a patch on this mod that would solve the issues of shells not spawning, and items being spawned more times than necessary.
However, **this is an awfully dirty patch**, so feel free to judge, rethink, or even decline anything about it.
(On the plus side, it's pretty short so you can understand quite easily what this does)

Unlockables.cs
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/55de5979-3ccc-4e13-bf74-7b2b75ecd080)

NewSave.cs
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/48447dce-7f8c-4d6f-8457-e30bb2fbee04)

**Comment by AndreyMrovol** [comment]
Hey, thanks for your report! I would not find this on my own (probably ever).
I've pushed v0.6.2 to Thunderstore - please check it out!

**Comment by Anonym-12321** [comment]
Thank you too! I'm quite flattered now ><
I just spent a bit of time comparing logs to formulate a theory, then i tried modifying and compiling your code to make sure i was right, with that and a couple of hours is how i got to that solution :3
Buut i do enjoy nerding out with programming in general so maybe that could also be why 😉

As for the update itself, you did apply the compatibility patch and it works!!! 
The bad news (only very slightly bad, it's nothing terrible :3) is that you forgot to also add code to prevent item groups from being spawned more than once:
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/d89ca715-ad99-4ff6-91df-05531088adf0)

Q: Why does this happens?
A: This happens because for some reason BetterShotgun creates a second Shell item, and a second and third Shotgun item. So your loop iterating through every possible item stumbles on Shell two times and on Shotgun three times, spawning double the shells and triple the shotguns compared to their respective intended amounts.

The fix is to assure that only the first time the items get spawned.
I did it with a very very (very) quick and dirty patch by adding `|| itemID > 67` on the `if(...) continue;` (like shown in the screenshot of my previous comment), which makes the loop skip on every item that doesn't have a vanilla id (thus skipping on all the added extra shotguns and shells)
A less crude, fancier and more flexible implementation would probably be this one:
```cs
using System.Collections.Generic;

// ...

   internal static void Spawn Items From Config()
   {
      HashSet<string> alreadySpawnedItems = new HashSet<string>(); // Keep track of already spawned items

      // Your code
      // ...
      
      foreach (Item item in allItemsList)
      {
         // ...
         
         if(alreadySpawnedItems.Contains(itemName)) continue; // Skip if the valid item is already spawned
         alreadySpawnedItems.Add(itemName); // Keep track of the item being spawned for the first time
         
         // More of your code, leaving it just for reference of where the patch is
         if (Unlockables.ItemsDictionary.ContainsKey(itemName))
         {
            // ...
         }
         else
         {
            // ...
         }
   }

// ...
```

Cheers!

**Comment by AndreyMrovol** [comment]
That's really interesting - I'll push a fix for that today.

**Comment by Anonym-12321** [comment]
Something even more interesting i just noticed:
The duplicate shells and shotguns (and the truplicate shotguns) generated by BetterShotgun v1.0.1 and spawned by UnlockOnStart v0.6.2 actually disappear after saving and reloading.

On new file creation (spread out for better demonstration):
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/ee4ee205-f163-43b0-a999-9f1b306d44de)

After saving and reloading:
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/1a5e0864-3390-4584-99d8-3ecdf3d8769c)

(Dropping the items outside and then back inside of the ship does not seem to change this behaviour)
I don't know why it happens, but i think it's worth noting for future reference in case you stumble on shotguns or ammo disappearing after saving and reloading.

**Comment by AndreyMrovol** [comment]
> That's really interesting - I'll push a fix for that today.

Turns out i've pushed a commit but forgot to update the mod in Thunderstore - version 0.6.3 is pushed right now, and should fix the duplicate spawning issue

**Comment by Anonym-12321** [comment]
Tested v0.6.3 now, in 5 out of 5 tests both the shotgun and the shell didn't duplicate, also the spawned version is the vanilla version.
Now it seems to be all working fine, i'm glad i could help!
I think it's safe to say this issue is now resolved :3
