### ISSUE TITLE
Suit options (feature request)

### ISSUE THREAD

**Issue by Anonym-12321** [AndreyMrovol/LethalUnlockOnStart#6]
They're both small changes, but i thought they would be worth implementing if you have the time to:
### Individual suit unlocks
Some people might want to have only one or few suits unlocked to leave the rest for purchase later like the 900 credits suit

### Unused purple suit
The game has an unused suit that as far as i remember works with no issues across clients, so i think it would be nice to allow it

**Comment by AndreyMrovol** [comment]
Hey, thanks for the suggestion! Although i originally didn't plan to include purple suit (for _challenge exclusivity_) or per-suit config option, this mod aims to be fully-configurable, so I'll happily include your proposal.

**Comment by Anonym-12321** [comment]
I can confirm, both changes seem to work as intended! Thank you very much!


> Hey, thanks for the suggestion! Although i originally didn't plan to include purple suit (for _challenge exclusivity_) or per-suit config option, this mod aims to be fully-configurable, so I'll happily include your proposal.

I somehow never realised it was always avaiable in challenge mode, whoops 😅
