### ISSUE TITLE
Shotguns do not seem to spawn in v0.5.0 and v0.6.0

### ISSUE THREAD

**Issue by Anonym-12321** [AndreyMrovol/LethalUnlockOnStart#7]
In v0.4.0 they seem to spawn just fine. In v0.5.0 and v0.6.0 i tried changing my configuration and disabling most mods, but it still didn't work.

**Comment by Anonym-12321** [comment]
After taking a few looks at the source code and logs, i think i narrowed down what could be the issue.
![immagine](https://github.com/AndreyMrovol/LethalUnlockOnStart/assets/157402858/058b2f0f-95ed-470c-9bd6-4cf80db637af)
The shotgun never gets debug logged, and i think that it might be because the game considers it as scrap.

Keep in mind that this is just my educated guess after browsing your github and looking at my logs, it's still possible i might be wrong.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - I'm gonna fix this ASAP.

**Comment by AndreyMrovol** [comment]
Quickly tested and can confirm - shotguns are considered scrap, which is something i've not tested properly (oops)
```log
[Debug  :UnlockOnStart] Item ID: 59 / Item name: Shotgun
[Debug  :UnlockOnStart] Is scrap: True
```

I've just pushed v0.6.1 - please check if it resolves your issue.

**Comment by Anonym-12321** [comment]
I can confirm, Shotguns in v0.6.1 spawn as intended. Thank you!

**Comment by Anonym-12321** [comment]
.
