### ISSUE TITLE
Keys (suggestion)

### ISSUE THREAD

**Issue by Anonym-12321** [AndreyMrovol/LethalUnlockOnStart#8]
Add keys as an unlockable on start, as a single-use alternative to the lockpicker.

(Small warning, the game probably considers key as scrap)

**Comment by AndreyMrovol** [comment]
Hey, I've pushed v0.6.2 to Thunderstore with your proposed change.

**Comment by Anonym-12321** [comment]
I can confirm, the key setting seems to work just fine!
