### ISSUE TITLE
Mod not taking effect when ShaosilGaming's GeneralImprovements is loaded

### ISSUE THREAD

**Issue by Re-VelatoR** [AndreyMrovol/LethalUnlockOnStart#9]
Unsure what is causing it. Can't find any related logs, but has something to do with a recent update to either mod.

**Comment by AndreyMrovol** [comment]
Hey, thanks for opening this issue and [the one on GeneralImprovements repo](https://github.com/Shaosil/LethalCompanyMods-GeneralImprovements/issues/81) - I believe your problem has been fixed.
